//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miku_UI_Music_Center.StringResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miku_UI_Music_Center.StringResources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Miku UI Audio Receiver 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Audio Forward DEBUG 的本地化字符串。
        /// </summary>
        public static string BtnStartAudioDbgText {
            get {
                return ResourceManager.GetString("BtnStartAudioDbgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string BtnStartText {
            get {
                return ResourceManager.GetString("BtnStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Forward 的本地化字符串。
        /// </summary>
        public static string CbAudioForwardText {
            get {
                return ResourceManager.GetString("CbAudioForwardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lyric Forward 的本地化字符串。
        /// </summary>
        public static string CbLyricForwardText {
            get {
                return ResourceManager.GetString("CbLyricForwardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose at least one option to forward! 的本地化字符串。
        /// </summary>
        public static string DlgSelectErrorSummaryText {
            get {
                return ResourceManager.GetString("DlgSelectErrorSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string DlgSelectErrorTitleText {
            get {
                return ResourceManager.GetString("DlgSelectErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lyrics will show in here 的本地化字符串。
        /// </summary>
        public static string TbLyricText {
            get {
                return ResourceManager.GetString("TbLyricText", resourceCulture);
            }
        }
    }
}
